// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAIaIXs5Tu88snv7f720Rt7I3bigbzPxo',
    appId: '1:318343793252:web:43d2f88c43b79540dbed71',
    messagingSenderId: '318343793252',
    projectId: 'flashcardapp-9756a',
    authDomain: 'flashcardapp-9756a.firebaseapp.com',
    storageBucket: 'flashcardapp-9756a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxnqJDhlkezNlvi4_HNiPZhacn4n99Cs8',
    appId: '1:318343793252:android:4791b3e40bf72e03dbed71',
    messagingSenderId: '318343793252',
    projectId: 'flashcardapp-9756a',
    storageBucket: 'flashcardapp-9756a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhYFLd3tBHAd3wHdAUjJxEjyfwaVGYoX4',
    appId: '1:318343793252:ios:0a67d6a3deb0368bdbed71',
    messagingSenderId: '318343793252',
    projectId: 'flashcardapp-9756a',
    storageBucket: 'flashcardapp-9756a.firebasestorage.app',
    iosBundleId: 'com.example.langapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhYFLd3tBHAd3wHdAUjJxEjyfwaVGYoX4',
    appId: '1:318343793252:ios:0a67d6a3deb0368bdbed71',
    messagingSenderId: '318343793252',
    projectId: 'flashcardapp-9756a',
    storageBucket: 'flashcardapp-9756a.firebasestorage.app',
    iosBundleId: 'com.example.langapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAIaIXs5Tu88snv7f720Rt7I3bigbzPxo',
    appId: '1:318343793252:web:1610ffaab10a36f3dbed71',
    messagingSenderId: '318343793252',
    projectId: 'flashcardapp-9756a',
    authDomain: 'flashcardapp-9756a.firebaseapp.com',
    storageBucket: 'flashcardapp-9756a.firebasestorage.app',
  );
}
